import {test} from 'node:test';
import assert from 'node:assert/strict';
import {sourceXxh3} from '@scientific-method/executable-reader';
import {loadResident,emulate,run} from '../../tools/emu/resident-call.mjs';
import {enginePython} from '../../tools/tool-dependencies.mjs';
const python=enginePython();
function toy(hex,callee){const code=Buffer.from(hex,'hex');const b=Buffer.alloc(32+(callee?20:code.length));b.write('MZ');b.writeUInt16LE(b.length,2);b.writeUInt16LE(1,4);b.writeUInt16LE(2,8);b.writeUInt16LE(28,24);code.copy(b,32);const regions=[{name:'synthetic-root',start:32,end:32+code.length,segment:0x1000,ip:0,entries:[32],evidence:'wholly synthetic CPU control'}];if(callee){b.writeUInt16LE(1,6);b.writeUInt16LE(3,28);Buffer.from('b82a00cb','hex').copy(b,48);regions.push({name:'synthetic-callee',start:48,end:52,segment:0x1000,ip:16,entries:[48],evidence:'synthetic returning callee'});}return {b,c:{sourceKind:'mz',xxh3:sourceXxh3(b),entry:32,regions}};}
const call=(t,extra={})=>emulate(loadResident(t.b,{...t.c,...extra}),python);
test('shared MZ relocation enters a real-mode far callee and returns through both frames',()=>{const t=toy('9a10000000cb',true);const p=loadResident(t.b,t.c);assert.equal(Buffer.from(p.image,'base64').readUInt16LE(3),0x1000);const r=emulate(p,python);assert(r.returned);assert.equal(r.registers.eax,42);assert(r.instructions.some(i=>i.region==='synthetic-callee'));assert.equal(r.steps,4);assert.equal(r.nativeReachability,'unconfirmed');});
test('resident identity, mappings, raw patches and an interior instruction entry are rejected',()=>{const t=toy('b82a00cb');assert.throws(()=>loadResident(t.b,{...t.c,xxh3:'0'.repeat(32)}),/xxh3/);assert.throws(()=>loadResident(t.b,{...t.c,memory:[]}),/seeding/);assert.throws(()=>loadResident(t.b,{...t.c,regions:t.c.regions.map(r=>({...r,segment:0x1001}))}),/mapping|resident load image/);assert.throws(()=>call(t,{entry:33,regions:t.c.regions.map(r=>({...r,entries:[33]}))}),/instruction start/);});
test('unread calls, mutation of declared code and non-returning loops fail closed',()=>{const t=toy('9a10000000cb',true);assert.throws(()=>call(t,{regions:t.c.regions.slice(0,1)}),/undeclared resident execution/);assert.throws(()=>call(toy('c606000090cb'),{registers:{ds:0x1000}}),/write to declared code/);assert.throws(()=>call(toy('ebfe'),{maxInstructions:8}),/instruction limit/);});
test('ordinary RAM writes and loaded-state comparisons are bounded, with no presentation claim',()=>{const r=call(toy('b800208ec0bf1000b07faacb'),{observations:[{name:'synthetic.destination.byte',segment:0x2000,offset:16,length:1}]});assert(r.returned);assert.equal(r.observations[0].before,'00');assert.equal(r.observations[0].after,'7f');assert(r.writes.some(w=>w.address===0x20010&&w.width===1&&w.value===127));assert.equal(r.presentation,'not tested');assert.throws(()=>call(toy('aacb'),{maxWrites:1,registers:{es:0x1000,edi:0}}),/write to declared code/);});
test('interrupts need named stop stubs and the overlay interrupt cannot be modeled',()=>{const t=toy('cd21cb');assert.throws(()=>call(t),/unmodeled interrupt 33.*offset.*0/);const r=call(t,{interrupts:[{vector:33,name:'synthetic_external_stop',action:'stop'}]});assert(!r.returned);assert.equal(r.stop,'synthetic_external_stop');assert.equal(r.hardware[0].offset,0);assert.throws(()=>call(toy('cd3fcb'),{interrupts:[{vector:63,name:'not_an_overlay_loader',action:'stop'}]}),/overlays cannot be loaded/);});
test('read and write ports are separately named, width-checked substitutions',()=>{const t=toy('ba3412eceecb');assert.throws(()=>call(t),/unmodeled port read 4660, width 1/);assert.throws(()=>call(t,{ports:[{port:0x1234,direction:'read',width:1,name:'synthetic_status_byte',value:42}]}),/unmodeled port write 4660, width 1/);const r=call(t,{ports:[{port:0x1234,direction:'read',width:1,name:'synthetic_status_byte',value:42},{port:0x1234,direction:'write',width:1,name:'synthetic_output_byte'}]});assert(r.returned);assert.deepEqual(r.hardware.map(e=>[e.kind,e.value]),[['port-read',42],['port-write',42]]);assert.throws(()=>call(t,{ports:[{port:0x1234,direction:'read',width:1,name:'too_wide',value:256}]}),/port value/);});
test('stack/image overlap, instruction bounds and observation bounds are rejected',()=>{const t=toy('b82a00cb');assert.throws(()=>call(toy('b82a00cb90909090'),{stackSegment:0x1000,stackOffset:4}),/return frame overlaps/);assert.throws(()=>call(t,{stackOffset:65535}),/stack offset/);assert.throws(()=>call(t,{observations:[{name:'synthetic.segment_crossing',segment:0x2000,offset:65535,length:2}]}),/segment offset limit/);assert.throws(()=>call(t,{maxInstructions:1}),/instruction limit/);assert.throws(()=>call(t,{observations:[{name:'synthetic.outside',segment:65535,offset:65535,length:2}]}),/observation/);});
test('the original-call CLI skips missing licensed content before loading a source',()=>{assert.throws(()=>run('unused.json',{}),/Set GAME_DIR/);});
// needs: GAME_DIR
// FND-CONFIG-193: optional licensed-source control; CI needs no proprietary content.
import {checkInitializer} from '../../tools/emu/check-initializer.mjs';
test('licensed resident initializer writes its known roots and flag bytes without seeding memory', {skip:!process.env.GAME_DIR?'needs GAME_DIR':false},()=>{const r=checkInitializer(process.env.GAME_DIR);assert.equal(r.negativeControls,'passed');assert(r.cases.every(c=>c.returned));});
