<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\DarkSunWakeRedux.Resources\DarkSunWakeRedux.Resources.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="RefurbishedDinosaurs.Media.Fli" Version="1.0.0" />
    <InternalsVisibleTo Include="DarkSunWakeRedux.Tests" />
  </ItemGroup>
</Project>
